### ISSUE TITLE
incomplete tabindex sequencing

### ISSUE THREAD

**Issue by lsmith** [ghinch/yui3-gallery#1]
It looks like the tabindexes are zero indexed and at least radios are not given tabindex.  0 is equivalent to not including a tabindex, making tab jump from the first element to the first element in the form without a tabindex.  You should start tabindex at 1 and specify a tabindex for all input/select/textarea/button elements.

**Comment by lsmith** [comment]
This is evident in your from-script example: http://ghinch.github.com/examples/form/example2.html

**Comment by ghinch** [comment]
Closed by 10bb6de6c0abe65e199178075409a1007778d55b, gh-2, gh-3, gh-4
