### ISSUE TITLE
Placeholder also executes when browser supports placeholders

### ISSUE THREAD

**Issue by mschipperheyn** [ghinch/yui3-gallery#14]
From the code there doesn't seem to be a distinction between browsers that do and don't support placeholders when this feature is primarily useful for browsers that don't

**Comment by ghinch** [comment]
Because of the fact that this can provide more than the standard browser implementation, right now there is no check, it's always added. I'm frankly also not sure how to check for browser support of the placeholder attribute conditionally.

**Comment by mschipperheyn** [comment]
You could do it based on browser versions simply

**Comment by ghinch** [comment]
I'd rather not put UA forking in module code like this, but you could wrap your plug() call in that check in your implementation if you are comfortable with it. I'll see if I can find a way to feature test
