### ISSUE TITLE
Placeholder will be sent on form submit

### ISSUE THREAD

**Issue by jtammen** [ghinch/yui3-gallery#16]
Hello,

I am using your module `gallery-placeholder` as a polyfill for browsers that don't natively support placeholders. I noticed that those placeholders added by the module will be submitted when the corresponding form gets submitted. I think this is not the expected behavior as "standard" placeholder will never be submitted...

[Test case - just hit Execute and then submit the form](http://tinkerbin.com/yxkv3n7L)

Thanks and greets,
Jan.

**Comment by ghinch** [comment]
That is correct. However, as the placeholder plugin is directly applied to the input node, and has no knowledge or connection of any form node, there's no good way to know when it is being "submitted". I'd suggest attaching an onsubmit listener that either unplugs the placeholders (in the case of a traditional submit) or gathers the values and ignores nodes currently showing placeholder text (in the case of a XHR submit)

**Comment by jtammen** [comment]
Hi Greg,

thanks for your quick reply.

Wouldn't it be possible to [find the corresponding form, which should be a parent of the input element, as others do it](http://www.hagenburger.net/BLOG/HTML5-Input-Placeholder-Fix-With-jQuery.html)?

I also stumbled upon the same problem in another situation: I have a `textarea` that uses the placeholder plugin and there are some other elements like buttons that manipulate the textarea's content – basically it takes the textarea's current text and adds some formatting tags to it. Problem is, that `node.value` will of course return the placeholder text if the user did not enter any text. Do you think it would be possible to circumvent this on a higher level so that using the plugin would be transparent? I think the text manipulating module should not be aware of the placeholder texts and have to care about removing them ... don't know if this is possible, but maybe a Node that has the plugin attached to it could be enhanced so that in the case it is still present, the placeholder text does not get returned as value...

**Comment by ghinch** [comment]
Certainly that would be possible, but I disagree with the logic presented by this (and most jQuery plugins). The intention here is a plugin for an input node which displays a placeholder value. While it can and likely will be used in connection with a form, the plugin itself should have no knowledge/connection to that form (loosely coupled). Your implementation can take care of the behavior you desire.

With the text area, again your implementation should take into account that the plugin is being used, check for the existence of it, and modify it's own behavior accordingly. So you could check if the node has the plugin, and the classname associated with showing the placeholder text, and in that case do not use node.value.

**Comment by jtammen** [comment]
Hi Greg,

I agree with you on the part about the loose coupling.

On the other hand, I think it also would make sense to not be forced to make other components that want to read a input's value aware of the fact that there might be a placeholder which has to be ignored... because, as I view it, the plugin serves as a transparent replacement for missing browser capabilities and should try to imitate the native placeholder's functionality.

Still don't know how to achieve this or how other plugins handle that – I will do some research on that.

Thanks for your input and greets,
Jan.

**Comment by ghinch** [comment]
While I understand wanting to be able to replace the default browser behavior, I would say the scope of this plugin isn't necessarily that for the form itself. What I would suggest is a separate node plugin for the form node, which uses the input placeholder plugin, and scans through all the form's fields, applying the input placeholder plugin as necessary. Since this form plugin would interact directly on the form node, it could take care of the functionality you describe.

**Comment by jtammen** [comment]
Greg,

you are right, the plugin should not know anything about form submitting. Your idea with the wrapping plugin sounds nice, but that won't solve my problem with other modules trying to read a textarea's value and have to remove the placeholder themselves. I think that it definitely is a input/textarea node's responsibility to not give out a value (may the requester be a form that wants to submit itself or any other component) when there really is just a placeholder ;-)

I will have a look at how the [Webshims lib](http://afarkas.github.com/webshim/demos/) handles this, as they claim: "The placeholder polyfill also works with getting and setting the value property (many other placeholder polyfills don't support this properly)"

Thanks again for your help and greets,
Jan.
