### ISSUE TITLE
_syncFieldNode on multi choiceField only checks 1 box

### ISSUE THREAD

**Issue by jindustry** [ghinch/yui3-gallery#9]
I tried to set a value for a choiceField with multi=true (set of checkboxes) like this  myMultiChoiceField.set('value', 'val1,val2') and ran into a couple of problems.

First, I had to call  myMultiChoiceField.syncUI()  explicity or the ui doesn't update.  I'm not sure if that's by design.
Second, the checkboxes do not update correctly after I call syncUI. The cuprit seems to be the following. The code seems to be written with radio buttons in mind and doesn't work for checkboxes. It never marks more than 1 checkbox AND never unmarks previously marked checkboxes.

```
    _syncFieldNode: function() {
        var choices = this.get('value').split(',');

        if (choices && choices.length > 0) {
            Y.Array.each(choices, function(choice) {
                this._fieldNode.each(function(node, index, list) {
                    if (Y.Lang.trim(node.get('value')) == Y.Lang.trim(choice)) {
                        node.set('checked', true);
                        return true;  // this will never check more than 1 box.
                        //previously checked boxes never get unchecked
                    }
                }, this);
            }, this);
        }
    },
```

The following changes seem to work.

```
    _syncFieldNode: function() {
        var choices = this.get('value').split(',');
        if (choices && choices.length > 0) {
            Y.Array.each(choices, function(choice) {
                choice = Y.Lang.trim(choice);
            });
            this._fieldNode.each(function(node, index, list) {
                var nodeValue = Y.Lang.trim(node.get('value'));
                if (Y.Array.indexOf(choices, nodeValue) > -1) {
                    node.set('checked', true);
                }
                else {
                    node.set('checked',false);
                }
            }, this);
        }
    },
```

**Comment by ghinch** [comment]
Thanks for finding this, I just committed the fix, which should also cover the problem of not updating after the value changes. Can you pull the latest code from my repo and confirm? Then I'll push it up to the CDN.

**Comment by jindustry** [comment]
I updated with your changes, Greg, but now I get an error: Y.Array.map is not a function http:/my/path/to/gallery-form.js Line 1577

I think you need to add 'collection' to the list of required modules. Other than that, it seems to work

**Comment by ghinch** [comment]
Hmm thats strange, I believe I did add collection to the requirements (see https://github.com/ghinch/yui3-gallery/commit/c3fda8a1ba7839d385207bf7eeb40e2987ae14fa#L2R1978). Are you loading the modules in the page yourself rather than using the Loader to dynamically insert them?

**Comment by jindustry** [comment]
Greg, your are correct, the problem was in my environment. I think your stuff works fine. Thanks for a very useful module!

**Comment by ghinch** [comment]
Ok great, I'll close this and request a CDN push with the fix. Glad to hear it's helpful!
